name: 'Setup Node Environment'
description: 'Checkout, setup node, and install dependencies with caching'

inputs:
  working-directory:
    description: 'The directory where the package.json is located'
    required: false
    default: '.' # defaults to root if not provided

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
